# Generated by Django 3.2.9 on 2021-11-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0002_auto_20211111_0100'),
        ('library_api', '0004_alter_book_books_img'),
    ]

    operations = [
    ]
